# modules/subdomain_enumeration/parser.py

from pathlib import Path
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(message)s")


class SubdomainParser:
    """
    Cleans and normalizes results generated by the Bash script.
    """

    def __init__(self, domain: str, out_base: str):
        self.domain = domain
        self.out_base = Path(out_base)
        self.work_dir = self.out_base / domain / "subenum"

    def parse_results(self, files: dict):
        subs_file = files.get("subdomains")
        alive_file = files.get("alive")

        subs = self._read_file(subs_file)
        alive = self._read_file(alive_file)

       
        subs = sorted(set(s.strip() for s in subs if s.strip()))
        alive = sorted(set(a.strip() for a in alive if a.strip()))

        logger.info(f"Parsed {len(subs)} subdomains, {len(alive)} alive hosts")
        return subs, alive

    def _read_file(self, path: Path):
        if not path or not path.exists():
            return []
        return path.read_text(errors="ignore").splitlines()
